meta_product_name: "Safeway"
meta_title: "Safeway - Find the safest way home"
meta_description: "Find the path which shows you the safest way home"
meta_image: "alert.png" # should exist in `app/assets/images/`