meta_product_name: "Safeway"
meta_title: "Safeway - Find the safest way home"
meta_description: "Avoid dangers and share your path with your friends!"
meta_image: "logolink.png" # should exist in `app/assets/images/`